/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import DAOs.CaixaDAO;
import DAOs.CarroDAO;
import DAOs.OperacoesDAO;
import Models.Caixa;
import Models.Carro;
import Models.Operacoes;
import TableModels.CarrosTableModel;
import TableModels.OperacoesTableModel;
import com.sun.corba.se.impl.logging.POASystemException;
import com.sun.media.sound.DLSModulator;
import java.lang.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.text.MaskFormatter;
import locadora.locadoradecarrosmaven.ConnectionFactory;

/**
 *
 * @author Mateus
 */
public class MainView extends javax.swing.JFrame {

    MaskFormatter mfData;

    public MainView() throws SQLException {
        try {
            mfData = new MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            throw new RuntimeException("erro mask");
        }
        initComponents();

//       ArrayList lista = new CarroDAO().selectAll();
//       lista.forEach(System.out::println);
        TableModels.CarrosTableModel tableModels = new TableModels.CarrosTableModel();
        jTableCarros.setModel(tableModels);
        TableModels.OperacoesTableModel tableModelsOp = new TableModels.OperacoesTableModel();
        jTableOperacoes.setModel(tableModelsOp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel39 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane7 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPlacaVenderPesquisa = new javax.swing.JTextField();
        jButtonPesquisarPlacaVender = new javax.swing.JButton();
        jButtonVenderCarro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldIDCarroVender = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldMarcaVender = new javax.swing.JTextField();
        jTextFieldModeloVender = new javax.swing.JTextField();
        jTextFieldAnoVender = new javax.swing.JTextField();
        jTextFieldPlacaVender = new javax.swing.JTextField();
        jTextFieldTipoVender = new javax.swing.JTextField();
        jTextFieldKMVender = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jTextFieldValorVender = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButtonComprar = new javax.swing.JButton();
        jTextFieldComprarMarca = new javax.swing.JTextField();
        jTextFieldComprarModelo = new javax.swing.JTextField();
        jTextFieldComprarAno = new javax.swing.JTextField();
        jTextFieldComprarPlaca = new javax.swing.JTextField();
        jTextFieldComprarKM = new javax.swing.JTextField();
        jComboBoxTipoComprar = new javax.swing.JComboBox<>();
        jLabel43 = new javax.swing.JLabel();
        jTextFieldComprarValor = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldRetirarBuscarPlaca = new javax.swing.JTextField();
        jButtonRetirarBuscar = new javax.swing.JButton();
        jTextFieldRetirarMarca = new javax.swing.JTextField();
        jTextFieldRetirarModelo = new javax.swing.JTextField();
        jTextFieldRetirarAno = new javax.swing.JTextField();
        jTextFieldRetirarKM = new javax.swing.JTextField();
        jTextFieldRetirarPLaca = new javax.swing.JTextField();
        jTextFieldRetirarTanque = new javax.swing.JTextField();
        jTextFieldRetirarTipo = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldRetirarID = new javax.swing.JTextField();
        jButtonRetirar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextFieldDevolverPlacaBusca = new javax.swing.JTextField();
        jTextFieldDevolverID = new javax.swing.JTextField();
        jTextFieldDevolverMarca = new javax.swing.JTextField();
        jTextFieldDevolverModelo = new javax.swing.JTextField();
        jTextFieldDevolverAno = new javax.swing.JTextField();
        jTextFieldDevolverKM = new javax.swing.JTextField();
        jTextFieldDevolverPlaca = new javax.swing.JTextField();
        jTextFieldDevolverTanque = new javax.swing.JTextField();
        jTextFieldDevolverTipo = new javax.swing.JTextField();
        jButtonDevolverBusca = new javax.swing.JButton();
        jButtonDevolver = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        jTextFieldDevolverTempo = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableOperacoes = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jFormattedTextFieldDataInicial = new javax.swing.JFormattedTextField(mfData);
        jFormattedTextFieldDataFinal = new javax.swing.JFormattedTextField(mfData);
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jButtonBuscarDataRelatorio = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCarros = new javax.swing.JTable();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jTextFieldCarrosFiltroMarca = new javax.swing.JTextField();
        jTextFieldCarroFiltroModelo = new javax.swing.JTextField();
        jComboBoxCarroFIltroTipo = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jTextFieldCarroValorMin = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jTextFieldCarroValorMax = new javax.swing.JTextField();
        jButtonCarrosValorBuscar = new javax.swing.JButton();
        jButtonCarroFiltroMarca = new javax.swing.JButton();
        jButtonCarroFiltroModelo = new javax.swing.JButton();
        jButtonCarroFiltroTipo = new javax.swing.JButton();
        jButtonTesteTable = new javax.swing.JButton();

        jLabel39.setText("jLabel39");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Placa :");

        jTextFieldPlacaVenderPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPlacaVenderPesquisaActionPerformed(evt);
            }
        });
        jTextFieldPlacaVenderPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPlacaVenderPesquisaKeyTyped(evt);
            }
        });

        jButtonPesquisarPlacaVender.setText("Pesquisar");
        jButtonPesquisarPlacaVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarPlacaVenderActionPerformed(evt);
            }
        });

        jButtonVenderCarro.setText("Vender");
        jButtonVenderCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVenderCarroActionPerformed(evt);
            }
        });

        jLabel1.setText("ID :");

        jTextFieldIDCarroVender.setEditable(false);

        jLabel3.setText("Marca :");

        jLabel4.setText("Modelo :");

        jLabel5.setText("Ano :");

        jLabel6.setText("Placa :");

        jLabel7.setText("Tipo :");

        jLabel8.setText("Kilometragem :");

        jTextFieldMarcaVender.setEditable(false);

        jTextFieldModeloVender.setEditable(false);
        jTextFieldModeloVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldModeloVenderActionPerformed(evt);
            }
        });

        jTextFieldAnoVender.setEditable(false);

        jTextFieldPlacaVender.setEditable(false);
        jTextFieldPlacaVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPlacaVenderActionPerformed(evt);
            }
        });

        jTextFieldTipoVender.setEditable(false);

        jTextFieldKMVender.setEditable(false);
        jTextFieldKMVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldKMVenderActionPerformed(evt);
            }
        });

        jLabel40.setText("Valor :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonVenderCarro)
                .addGap(62, 62, 62))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldValorVender, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldKMVender, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldIDCarroVender, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPlacaVenderPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPesquisarPlacaVender))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldTipoVender))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldPlacaVender))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldMarcaVender, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(25, 25, 25)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldModeloVender)
                                .addComponent(jTextFieldAnoVender)))))
                .addContainerGap(725, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPlacaVenderPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisarPlacaVender))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldIDCarroVender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldMarcaVender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldModeloVender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldAnoVender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldPlacaVender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldTipoVender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldKMVender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(jTextFieldValorVender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(jButtonVenderCarro)
                .addGap(44, 44, 44))
        );

        jTabbedPane7.addTab("Vender", jPanel2);

        jLabel9.setText("Placa :");

        jLabel10.setText("Modelo :");

        jLabel11.setText("Tipo :");

        jLabel12.setText("Kilometragem :");

        jLabel13.setText("Marca :");

        jLabel14.setText("Ano :");

        jButtonComprar.setText("Comprar");
        jButtonComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprarActionPerformed(evt);
            }
        });

        jTextFieldComprarAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldComprarAnoActionPerformed(evt);
            }
        });

        jComboBoxTipoComprar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Economico", "Sedan", "SUV", "Premium" }));

        jLabel43.setText("Valor :");

        jTextFieldComprarValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldComprarValorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonComprar)
                .addGap(78, 78, 78))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel43)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldComprarValor, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldComprarKM))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldComprarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel14))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldComprarModelo)
                                .addComponent(jTextFieldComprarAno)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel11))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldComprarPlaca)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jComboBoxTipoComprar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addContainerGap(773, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldComprarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldComprarModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldComprarAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldComprarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBoxTipoComprar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldComprarKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(jTextFieldComprarValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 253, Short.MAX_VALUE)
                .addComponent(jButtonComprar)
                .addGap(52, 52, 52))
        );

        jTabbedPane7.addTab("Comprar", jPanel3);

        jLabel15.setText("Marca :");

        jLabel16.setText("Modelo :");

        jLabel17.setText("Ano :");

        jLabel18.setText("Kilometragem :");

        jLabel19.setText("Placa :");

        jLabel20.setText("Tanque :");

        jLabel21.setText("Tipo :");

        jLabel22.setText("Placa :");

        jButtonRetirarBuscar.setText("Buscar");
        jButtonRetirarBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetirarBuscarActionPerformed(evt);
            }
        });

        jTextFieldRetirarMarca.setEditable(false);

        jTextFieldRetirarModelo.setEditable(false);

        jTextFieldRetirarAno.setEditable(false);

        jTextFieldRetirarKM.setEditable(false);

        jTextFieldRetirarPLaca.setEditable(false);

        jTextFieldRetirarTanque.setEditable(false);

        jTextFieldRetirarTipo.setEditable(false);

        jLabel23.setText("ID :");

        jTextFieldRetirarID.setEditable(false);

        jButtonRetirar.setText("Retirar");
        jButtonRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetirarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldRetirarKM, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldRetirarBuscarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(jLabel15)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                            .addComponent(jLabel16)
                                            .addGap(1, 1, 1)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(20, 20, 20))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addGap(31, 31, 31)))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldRetirarAno)
                                    .addComponent(jTextFieldRetirarMarca)
                                    .addComponent(jTextFieldRetirarModelo)
                                    .addComponent(jTextFieldRetirarID))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRetirarBuscar))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldRetirarPLaca)
                            .addComponent(jTextFieldRetirarTanque)
                            .addComponent(jTextFieldRetirarTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))))
                .addContainerGap(781, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRetirar)
                .addGap(43, 43, 43))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTextFieldRetirarBuscarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRetirarBuscar))
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jTextFieldRetirarID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldRetirarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldRetirarModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextFieldRetirarAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextFieldRetirarKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextFieldRetirarPLaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextFieldRetirarTanque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTextFieldRetirarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                .addComponent(jButtonRetirar)
                .addGap(29, 29, 29))
        );

        jTabbedPane7.addTab("Retirar", jPanel4);

        jLabel24.setText("Placa :");

        jLabel25.setText("ID :");

        jLabel26.setText("Marca :");

        jLabel27.setText("Modelo :");

        jLabel28.setText("Ano :");

        jLabel29.setText("Kilometragem :");

        jLabel30.setText("Placa :");

        jLabel31.setText("Tanque :");

        jLabel32.setText("Tipo: ");

        jTextFieldDevolverID.setEditable(false);

        jTextFieldDevolverMarca.setEditable(false);

        jTextFieldDevolverModelo.setEditable(false);

        jTextFieldDevolverAno.setEditable(false);

        jTextFieldDevolverPlaca.setEditable(false);

        jTextFieldDevolverTipo.setEditable(false);

        jButtonDevolverBusca.setText("Buscar");
        jButtonDevolverBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDevolverBuscaActionPerformed(evt);
            }
        });

        jButtonDevolver.setText("Devolver");
        jButtonDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDevolverActionPerformed(evt);
            }
        });

        jLabel44.setText("Tempo de Aluguel (DIAS) :");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDevolverPlacaBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDevolverBusca))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDevolverKM, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addGap(43, 43, 43)
                                        .addComponent(jTextFieldDevolverID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel27)
                                            .addComponent(jLabel28))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldDevolverModelo)
                                            .addComponent(jTextFieldDevolverAno))))
                                .addGap(115, 115, 115))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDevolverTipo))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel31))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldDevolverTanque, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jTextFieldDevolverPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(50, 50, 50)
                        .addComponent(jLabel44)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDevolverTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldDevolverMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(871, 871, 871))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonDevolver)
                .addGap(29, 29, 29))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jTextFieldDevolverPlacaBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDevolverBusca)
                    .addComponent(jLabel44)
                    .addComponent(jTextFieldDevolverTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jTextFieldDevolverID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jTextFieldDevolverMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jTextFieldDevolverModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jTextFieldDevolverAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jTextFieldDevolverKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jTextFieldDevolverPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jTextFieldDevolverTanque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jTextFieldDevolverTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
                .addComponent(jButtonDevolver)
                .addGap(21, 21, 21))
        );

        jTabbedPane7.addTab("Devolver", jPanel5);

        jTableOperacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableOperacoes);

        jButton2.setText("refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jFormattedTextFieldDataInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldDataInicialActionPerformed(evt);
            }
        });

        jFormattedTextFieldDataFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldDataFinalActionPerformed(evt);
            }
        });

        jLabel41.setText("Data Inicial :");

        jLabel42.setText("Data Final :");

        jButtonBuscarDataRelatorio.setText("Buscar");
        jButtonBuscarDataRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarDataRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonBuscarDataRelatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 459, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(28, 28, 28))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jFormattedTextFieldDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41)
                    .addComponent(jLabel42)
                    .addComponent(jFormattedTextFieldDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarDataRelatorio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane7.addTab("Relatorio", jPanel6);

        jTableCarros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableCarros);

        jLabel33.setText("Marca :");

        jLabel34.setText("Modelo :");

        jLabel35.setText("Tipo :");

        jComboBoxCarroFIltroTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Economico", "Sedan", "SUV", "Premium" }));

        jLabel36.setText("Preço :");

        jLabel37.setText("Valor Min. :");

        jTextFieldCarroValorMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCarroValorMinActionPerformed(evt);
            }
        });

        jLabel38.setText("Valor Max. :");

        jButtonCarrosValorBuscar.setText("Buscar");
        jButtonCarrosValorBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarrosValorBuscarActionPerformed(evt);
            }
        });

        jButtonCarroFiltroMarca.setText("Buscar");
        jButtonCarroFiltroMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarroFiltroMarcaActionPerformed(evt);
            }
        });

        jButtonCarroFiltroModelo.setText("Buscar");
        jButtonCarroFiltroModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarroFiltroModeloActionPerformed(evt);
            }
        });

        jButtonCarroFiltroTipo.setText("Buscar");
        jButtonCarroFiltroTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarroFiltroTipoActionPerformed(evt);
            }
        });

        jButtonTesteTable.setText("teste");
        jButtonTesteTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTesteTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldCarrosFiltroMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCarroFiltroMarca)
                        .addGap(136, 136, 136)
                        .addComponent(jLabel36))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addComponent(jLabel35))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldCarroFiltroModelo)
                            .addComponent(jComboBoxCarroFIltroTipo, 0, 107, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jButtonCarroFiltroModelo)
                                .addGap(164, 164, 164)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel37)
                                    .addComponent(jLabel38)))
                            .addComponent(jButtonCarroFiltroTipo))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldCarroValorMin)
                    .addComponent(jTextFieldCarroValorMax, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(jButtonCarrosValorBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addComponent(jButtonTesteTable)
                .addGap(48, 48, 48))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(jTextFieldCarrosFiltroMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36)
                            .addComponent(jButtonCarroFiltroMarca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(jTextFieldCarroFiltroModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCarroFiltroModelo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(jComboBoxCarroFIltroTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCarroFiltroTipo)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel37)
                            .addComponent(jTextFieldCarroValorMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(jTextFieldCarroValorMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCarrosValorBuscar)
                            .addComponent(jButtonTesteTable))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane7.addTab("Carros", jPanel7);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane7)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane7)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPlacaVenderPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPlacaVenderPesquisaActionPerformed


    }//GEN-LAST:event_jTextFieldPlacaVenderPesquisaActionPerformed

    private void jTextFieldPlacaVenderPesquisaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPlacaVenderPesquisaKeyTyped

        if (jTextFieldPlacaVenderPesquisa.getText().length() >= 8) {
            evt.consume();
        }

    }//GEN-LAST:event_jTextFieldPlacaVenderPesquisaKeyTyped

    private void jTextFieldModeloVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldModeloVenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldModeloVenderActionPerformed

    private void jTextFieldKMVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldKMVenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldKMVenderActionPerformed

    private void jButtonPesquisarPlacaVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarPlacaVenderActionPerformed
        Carro carro = new Carro();
        String placa = jTextFieldPlacaVenderPesquisa.getText().trim();
        System.out.println(placa);
        try {
//            CarroDAO.listar();
            carro = CarroDAO.pesquisaVenda(placa);

            jTextFieldIDCarroVender.setText(Integer.toString(carro.getId()));
            jTextFieldMarcaVender.setText(carro.getMarca());
            jTextFieldModeloVender.setText(carro.getModelo());
            jTextFieldAnoVender.setText(Integer.toString(carro.getAno()));
            jTextFieldPlacaVender.setText(carro.getPlaca());
            jTextFieldTipoVender.setText(carro.getTipo());
            jTextFieldKMVender.setText(Integer.toString((int) carro.getKilometragem()));

        } catch (Exception ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonPesquisarPlacaVenderActionPerformed

    private void jTextFieldPlacaVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPlacaVenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlacaVenderActionPerformed

    private void jTextFieldComprarAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldComprarAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldComprarAnoActionPerformed

    private void jButtonVenderCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVenderCarroActionPerformed
        String placa = jTextFieldPlacaVender.getText();
        if (placa.equals("")) {
            JOptionPane.showMessageDialog(null, "Placa Invalida");
        } else {
            try {

                Operacoes novaOperacao = new Operacoes();

                novaOperacao.setTipo("VENDA");
                System.out.println(novaOperacao.getTipo());
                novaOperacao.setCarro(Integer.parseInt(jTextFieldIDCarroVender.getText().trim()));
                System.out.println(novaOperacao.getCarro());
                novaOperacao.setKilometragem(Float.parseFloat(jTextFieldKMVender.getText()));
                System.out.println(novaOperacao.getKilometragem());
                novaOperacao.setTanque(0);
                System.out.println(novaOperacao.getTanque());
                novaOperacao.setValor(Double.parseDouble(jTextFieldValorVender.getText()));
                System.out.println(novaOperacao.getValor());
                OperacoesDAO.insert(novaOperacao);

                CarroDAO.vender(placa);

                JOptionPane.showMessageDialog(null, "Venda Realizada com sucesso");
                jTextFieldIDCarroVender.setText("");
                jTextFieldMarcaVender.setText("");
                jTextFieldModeloVender.setText("");
                jTextFieldAnoVender.setText("");
                jTextFieldPlacaVender.setText("");
                jTextFieldTipoVender.setText("");
                jTextFieldKMVender.setText("");

            } catch (Exception ex) {
                Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        
        
    }//GEN-LAST:event_jButtonVenderCarroActionPerformed

    private void jButtonComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprarActionPerformed

        try {

            Carro novoCarro = new Carro();

            novoCarro.setMarca(jTextFieldComprarMarca.getText().trim());
            novoCarro.setModelo(jTextFieldComprarModelo.getText().trim());
            novoCarro.setAno(Integer.parseInt(jTextFieldComprarAno.getText().trim()));
            novoCarro.setPlaca(jTextFieldComprarPlaca.getText().trim());
            novoCarro.setTipo(jComboBoxTipoComprar.getSelectedItem().toString());
            novoCarro.setKilometragem(Float.parseFloat(jTextFieldComprarKM.getText()));
            novoCarro.setTanque(1);
            novoCarro.setDisponibilidade(true);
            novoCarro.setPreco(Double.parseDouble(jTextFieldComprarValor.getText()));

            try {
                CarroDAO.comprar(novoCarro);
            } catch (Exception ex) {
                Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
            }

            Operacoes novaOperacao = new Operacoes();

            novaOperacao.setTipo("COMPRA");

            novaOperacao.setCarro(CarroDAO.buscaMaiorId());

            novaOperacao.setKilometragem(Float.parseFloat(jTextFieldComprarKM.getText()));

            novaOperacao.setTanque(0);

            novaOperacao.setValor(Double.parseDouble("-"+jTextFieldComprarValor.getText()));
            System.out.println(novaOperacao.getValor());
            try {
                OperacoesDAO.insert(novaOperacao);
            } catch (Exception ex) {
                Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (Exception ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonComprarActionPerformed

    private void jButtonRetirarBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetirarBuscarActionPerformed
        Carro carro = new Carro();
        String placa = jTextFieldRetirarBuscarPlaca.getText().trim();
        System.out.println(placa);
        try {
//            CarroDAO.listar();
            carro = CarroDAO.pesquisaVenda(placa);

            jTextFieldRetirarID.setText(Integer.toString(carro.getId()));
            jTextFieldRetirarMarca.setText(carro.getMarca());
            jTextFieldRetirarModelo.setText(carro.getModelo());
            jTextFieldRetirarAno.setText(Integer.toString(carro.getAno()));
            jTextFieldRetirarPLaca.setText(carro.getPlaca());
            jTextFieldRetirarTipo.setText(carro.getTipo());
            jTextFieldRetirarTanque.setText(Integer.toString(carro.getTanque()));
            jTextFieldRetirarKM.setText(Integer.toString((int) carro.getKilometragem()));

        } catch (Exception ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonRetirarBuscarActionPerformed

    private void jButtonRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetirarActionPerformed

        String placa = jTextFieldRetirarPLaca.getText().trim();

        try {
            if (CarroDAO.checaDisponibilidade(placa) == true) {
                Operacoes novaOperacao = new Operacoes();

                novaOperacao.setTipo("RETIRADA");
                novaOperacao.setCarro(Integer.parseInt(jTextFieldRetirarID.getText().trim()));
                novaOperacao.setKilometragem(Float.parseFloat(jTextFieldRetirarKM.getText()));
                novaOperacao.setTanque(Integer.parseInt(jTextFieldRetirarTanque.getText()));
                novaOperacao.setValor(0);
                OperacoesDAO.insert(novaOperacao);
                JOptionPane.showMessageDialog(null, "Carro retirado com sucesso");
            } else {
                JOptionPane.showMessageDialog(null, "Carro Indisponivel");
            }

        } catch (Exception ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButtonRetirarActionPerformed

    private void jButtonDevolverBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDevolverBuscaActionPerformed

        Carro carro = new Carro();
        String placa = jTextFieldDevolverPlacaBusca.getText().trim();
        System.out.println(placa);
        try {
            carro = CarroDAO.pesquisaVenda(placa);
            jTextFieldDevolverID.setText(Integer.toString(carro.getId()));
            jTextFieldDevolverMarca.setText(carro.getMarca());
            jTextFieldDevolverModelo.setText(carro.getModelo());
            jTextFieldDevolverAno.setText(Integer.toString(carro.getAno()));
            jTextFieldDevolverPlaca.setText(carro.getPlaca());
            jTextFieldDevolverTipo.setText(carro.getTipo());
            jTextFieldDevolverKM.setText(Integer.toString((int) carro.getKilometragem()));
            jTextFieldDevolverTanque.setText(Integer.toString(carro.getTanque()));

        } catch (Exception ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButtonDevolverBuscaActionPerformed

    private void jButtonDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDevolverActionPerformed
        String placa = jTextFieldDevolverPlaca.getText().trim();

        try {
            if (CarroDAO.checaIndisponibilidade(placa) == true) {
                Operacoes novaOperacao = new Operacoes();

                novaOperacao.setTipo("DEVOLUCAO");
                novaOperacao.setCarro(Integer.parseInt(jTextFieldDevolverID.getText().trim()));
                novaOperacao.setKilometragem(Float.parseFloat(jTextFieldDevolverKM.getText()));
                novaOperacao.setTanque(Integer.parseInt(jTextFieldDevolverTanque.getText()));
                novaOperacao.setValor(Double.parseDouble(jTextFieldDevolverTempo.getText().trim()) * 75);
                OperacoesDAO.insert(novaOperacao);
                JOptionPane.showMessageDialog(null, "Carro devolvido com sucesso");
            } else {
                JOptionPane.showMessageDialog(null, "Carro nao foi retirado");
            }

        } catch (Exception ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonDevolverActionPerformed

    private void jButtonTesteTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTesteTableActionPerformed
        ArrayList<Carro> list = new ArrayList<>();
        String tipo = jComboBoxCarroFIltroTipo.getSelectedItem().toString().trim();
        try {
            CarrosTableModel tableModels = new CarrosTableModel();

            list = CarroDAO.selectTipo(tipo);
            tableModels.setList(list);
            jTableCarros.setModel(tableModels);
            System.out.println(tipo);
            System.out.println("entrou");
        } catch (SQLException ex) {
            throw new RuntimeException("n entrou teste");
        }


    }//GEN-LAST:event_jButtonTesteTableActionPerformed

    private void jButtonCarroFiltroTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarroFiltroTipoActionPerformed

        ArrayList<Carro> list = new ArrayList<>();
        String tipo = jComboBoxCarroFIltroTipo.getSelectedItem().toString().trim();
        try {
            CarrosTableModel tableModels = new CarrosTableModel();

            list = CarroDAO.selectTipo(tipo);
            tableModels.setList(list);
            jTableCarros.setModel(tableModels);
            System.out.println(tipo);
            System.out.println("entrou");
        } catch (SQLException ex) {
            throw new RuntimeException("n entrou teste");
        }

    }//GEN-LAST:event_jButtonCarroFiltroTipoActionPerformed

    private void jButtonCarroFiltroModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarroFiltroModeloActionPerformed

        ArrayList<Carro> list = new ArrayList<>();
        String modelo = jTextFieldCarroFiltroModelo.getText().trim();
        try {
            CarrosTableModel tableModels = new CarrosTableModel();

            list = CarroDAO.selectModelo(modelo);
            tableModels.setList(list);
            jTableCarros.setModel(tableModels);
            System.out.println(modelo);
            System.out.println("entrou");
        } catch (SQLException ex) {
            throw new RuntimeException("n entrou teste");
        }

    }//GEN-LAST:event_jButtonCarroFiltroModeloActionPerformed

    private void jButtonCarroFiltroMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarroFiltroMarcaActionPerformed

        ArrayList<Carro> list = new ArrayList<>();
        String marca = jTextFieldCarrosFiltroMarca.getText().trim();
        try {
            CarrosTableModel tableModels = new CarrosTableModel();

            list = CarroDAO.selectMarca(marca);
            tableModels.setList(list);
            jTableCarros.setModel(tableModels);
            System.out.println(marca);
            System.out.println("entrou");
        } catch (SQLException ex) {
            throw new RuntimeException("n entrou teste");
        }


    }//GEN-LAST:event_jButtonCarroFiltroMarcaActionPerformed

    private void jFormattedTextFieldDataFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDataFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldDataFinalActionPerformed

    private void jFormattedTextFieldDataInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDataInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldDataInicialActionPerformed

    private void jButtonBuscarDataRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarDataRelatorioActionPerformed
        String dataInicial = jFormattedTextFieldDataInicial.getText().trim();
        System.out.println(dataInicial);
        String dataFinal = jFormattedTextFieldDataFinal.getText().trim();
        System.out.println(dataFinal);

        dataInicial = dataInicial.replace("/", "-");
        dataFinal = dataFinal.replace("/", "-");
        System.out.println(dataInicial);

        String[] dataInicialSeparada = dataInicial.split("-");
        String[] dataFinalSeparada = dataFinal.split("-");
        String dataInicialTratada = dataInicialSeparada[2] + "-" + dataInicialSeparada[1] + "-" + dataInicialSeparada[0];
        String dataFinalTratada = dataFinalSeparada[2] + "-" + dataFinalSeparada[1] + "-" + dataFinalSeparada[0];
        System.out.println(dataInicialTratada);
        System.out.println(dataFinalTratada);

        ArrayList<Operacoes> list = new ArrayList<>();
        String marca = jTextFieldCarrosFiltroMarca.getText().trim();
        try {
            OperacoesTableModel tableModelsOp = new OperacoesTableModel();

            list = OperacoesDAO.selectData(dataInicialTratada, dataFinalTratada);
            tableModelsOp.setList(list);
            jTableCarros.setModel(tableModelsOp);
            System.out.println(marca);
            System.out.println("entrou");
        } catch (SQLException ex) {
            throw new RuntimeException("n entrou teste");
        }
    }//GEN-LAST:event_jButtonBuscarDataRelatorioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            TableModels.OperacoesTableModel tableModelsOp = new TableModels.OperacoesTableModel();
            jTableOperacoes.setModel(tableModelsOp);
        } catch (SQLException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonCarrosValorBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarrosValorBuscarActionPerformed

        ArrayList<Carro> list = new ArrayList<>();
        try {

            double valorMin = Double.parseDouble(jTextFieldCarroValorMin.getText().trim());
            double valorMax = Double.parseDouble(jTextFieldCarroValorMax.getText().trim());
            System.out.println(valorMin);
            System.out.println(valorMax);

            CarrosTableModel tableModels = new CarrosTableModel();
            list = CarroDAO.selectValor(valorMin, valorMax);
            tableModels.setList(list);
            jTableCarros.setModel(tableModels);
            System.out.println("sadiahd");
        } catch (SQLException ex) {
            throw new RuntimeException("DSANDHAKSHFS");
        }


    }//GEN-LAST:event_jButtonCarrosValorBuscarActionPerformed

    private void jTextFieldCarroValorMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCarroValorMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCarroValorMinActionPerformed

    private void jTextFieldComprarValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldComprarValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldComprarValorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainView().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonBuscarDataRelatorio;
    private javax.swing.JButton jButtonCarroFiltroMarca;
    private javax.swing.JButton jButtonCarroFiltroModelo;
    private javax.swing.JButton jButtonCarroFiltroTipo;
    private javax.swing.JButton jButtonCarrosValorBuscar;
    private javax.swing.JButton jButtonComprar;
    private javax.swing.JButton jButtonDevolver;
    private javax.swing.JButton jButtonDevolverBusca;
    private javax.swing.JButton jButtonPesquisarPlacaVender;
    private javax.swing.JButton jButtonRetirar;
    private javax.swing.JButton jButtonRetirarBuscar;
    private javax.swing.JButton jButtonTesteTable;
    private javax.swing.JButton jButtonVenderCarro;
    private javax.swing.JComboBox<String> jComboBoxCarroFIltroTipo;
    private javax.swing.JComboBox<String> jComboBoxTipoComprar;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataFinal;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JTable jTableCarros;
    private javax.swing.JTable jTableOperacoes;
    private javax.swing.JTextField jTextFieldAnoVender;
    private javax.swing.JTextField jTextFieldCarroFiltroModelo;
    private javax.swing.JTextField jTextFieldCarroValorMax;
    private javax.swing.JTextField jTextFieldCarroValorMin;
    private javax.swing.JTextField jTextFieldCarrosFiltroMarca;
    private javax.swing.JTextField jTextFieldComprarAno;
    private javax.swing.JTextField jTextFieldComprarKM;
    private javax.swing.JTextField jTextFieldComprarMarca;
    private javax.swing.JTextField jTextFieldComprarModelo;
    private javax.swing.JTextField jTextFieldComprarPlaca;
    private javax.swing.JTextField jTextFieldComprarValor;
    private javax.swing.JTextField jTextFieldDevolverAno;
    private javax.swing.JTextField jTextFieldDevolverID;
    private javax.swing.JTextField jTextFieldDevolverKM;
    private javax.swing.JTextField jTextFieldDevolverMarca;
    private javax.swing.JTextField jTextFieldDevolverModelo;
    private javax.swing.JTextField jTextFieldDevolverPlaca;
    private javax.swing.JTextField jTextFieldDevolverPlacaBusca;
    private javax.swing.JTextField jTextFieldDevolverTanque;
    private javax.swing.JTextField jTextFieldDevolverTempo;
    private javax.swing.JTextField jTextFieldDevolverTipo;
    private javax.swing.JTextField jTextFieldIDCarroVender;
    private javax.swing.JTextField jTextFieldKMVender;
    private javax.swing.JTextField jTextFieldMarcaVender;
    private javax.swing.JTextField jTextFieldModeloVender;
    private javax.swing.JTextField jTextFieldPlacaVender;
    private javax.swing.JTextField jTextFieldPlacaVenderPesquisa;
    private javax.swing.JTextField jTextFieldRetirarAno;
    private javax.swing.JTextField jTextFieldRetirarBuscarPlaca;
    private javax.swing.JTextField jTextFieldRetirarID;
    private javax.swing.JTextField jTextFieldRetirarKM;
    private javax.swing.JTextField jTextFieldRetirarMarca;
    private javax.swing.JTextField jTextFieldRetirarModelo;
    private javax.swing.JTextField jTextFieldRetirarPLaca;
    private javax.swing.JTextField jTextFieldRetirarTanque;
    private javax.swing.JTextField jTextFieldRetirarTipo;
    private javax.swing.JTextField jTextFieldTipoVender;
    private javax.swing.JTextField jTextFieldValorVender;
    // End of variables declaration//GEN-END:variables
}
